PYTHONPATH ?= ../../
PYTHON     ?= python

.PHONY: run-intro compare

run-intro:
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m ChaptersFinancial.ch13_fin.listings.pyg_intro_counterparty

compare:
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m ChaptersFinancial.ch13_fin.listings.compare_architectures
