"""
Listing 04 – Compliance Guardrails
====================================
Demonstrates how to add compliance and safety guardrails to every LLM call:
  1. Input guardrail  – strip or refuse requests for PII, price targets, predictions.
  2. Output guardrail – flag speculative statements, add mandatory disclaimers.
  3. Schema guardrail – validate JSON output against the target schema and reject
                        responses that claim confidence > 0.95 without a citation.

This listing is educational: it shows how to wrap the LLMProvider with a
GuardedLLMProvider that enforces these rules transparently.

Run:
    cd <repo_root>
    LLM_PROVIDER=mock python -m ChaptersFinancial.ch02_fin.listings.04_compliance_guardrails
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from ChaptersFinancial._platform.providers.llm import LLMProvider

_SCHEMA_PATH = Path(__file__).parent.parent / "schemas" / "entity_extraction.schema.json"
_SCHEMA = json.loads(_SCHEMA_PATH.read_text())

# ------------------------------------------------------------------
# Guardrail patterns
# ------------------------------------------------------------------

# Patterns in user prompts that must be refused
_FORBIDDEN_INPUT_PATTERNS = [
    re.compile(r"\bprice\s+target\b", re.I),
    re.compile(r"\bbuy\s+recommendation\b", re.I),
    re.compile(r"\bshould\s+I\s+(buy|sell|invest)\b", re.I),
    re.compile(r"\b(SSN|social\s+security\s+number|passport\s+number)\b", re.I),
]

# Words in model output that require a compliance flag
_SPECULATIVE_PATTERNS = [
    re.compile(r"\bwill\s+(increase|decrease|grow|fall|rise|drop)\b", re.I),
    re.compile(r"\bexpect(ed)?\s+to\b", re.I),
    re.compile(r"\bforecast\b", re.I),
    re.compile(r"\bproject(ed|ion)?\b", re.I),
]

_MANDATORY_DISCLAIMER = (
    "DISCLAIMER: This output is generated by an AI system and does not constitute "
    "financial advice, investment recommendations, or regulatory guidance."
)


class ComplianceError(ValueError):
    """Raised when a prompt violates compliance guardrails."""


class GuardedLLMProvider:
    """
    Wraps LLMProvider with input/output/schema guardrails.
    Drop-in replacement: exposes the same complete_json() interface.
    """

    def __init__(self, inner: LLMProvider | None = None):
        self._inner = inner or LLMProvider()

    def complete_json(
        self,
        prompt: str,
        schema: dict | None = None,
        *,
        system: str = "",
        temperature: float | None = None,
        model: str | None = None,
    ) -> dict:
        # ── Input guardrail ──────────────────────────────────────────
        self._check_input(prompt)

        # ── Call underlying provider ─────────────────────────────────
        result = self._inner.complete_json(
            prompt, schema, system=system, temperature=temperature, model=model
        )

        # ── Output guardrail ─────────────────────────────────────────
        result = self._check_output(result)

        return result

    # ------------------------------------------------------------------
    # Guardrail methods
    # ------------------------------------------------------------------
    def _check_input(self, prompt: str) -> None:
        for pattern in _FORBIDDEN_INPUT_PATTERNS:
            if pattern.search(prompt):
                raise ComplianceError(
                    f"Input blocked: prompt matches forbidden pattern '{pattern.pattern}'. "
                    "Remove investment advice requests or PII from the prompt."
                )

    def _check_output(self, result: dict) -> dict:
        # 1. Flag high-confidence entities that lack context
        entities = result.get("entities", [])
        for ent in entities:
            if float(ent.get("confidence", 0)) > 0.95 and not ent.get("context"):
                ent["confidence"] = 0.95  # cap confidence without citation
                ent.setdefault("compliance_note", "Confidence capped: no context provided")

        # 2. Detect speculative language in free-text fields
        text_blob = json.dumps(result)
        speculative_matches = [p.pattern for p in _SPECULATIVE_PATTERNS if p.search(text_blob)]
        if speculative_matches:
            result["speculative_language_detected"] = speculative_matches

        # 3. Always attach disclaimer
        result["disclaimer"] = _MANDATORY_DISCLAIMER

        return result


# ------------------------------------------------------------------
# Demonstration
# ------------------------------------------------------------------
def _demo_safe_prompt():
    print("── SAFE PROMPT ──────────────────────────────")
    provider = GuardedLLMProvider()
    text = "Berkshire Hathaway (BRK.A) reported operating earnings of $11.2 billion for Q2 2024."
    prompt = (
        f"Extract financial entities from this text.\n\nTEXT:\n{text}\n\n"
        "Return JSON with key 'entities' (array of objects with text, label, confidence)."
    )
    result = provider.complete_json(prompt, schema=_SCHEMA)
    print(json.dumps(result, indent=2))


def _demo_forbidden_prompt():
    print("\n── FORBIDDEN PROMPT ─────────────────────────")
    provider = GuardedLLMProvider()
    prompt = "Should I buy NVDA? What's the price target for NVIDIA?"
    try:
        provider.complete_json(prompt)
        print("ERROR: Should have raised ComplianceError!")
    except ComplianceError as exc:
        print(f"✓ Correctly blocked: {exc}")


def _demo_speculative_output():
    print("\n── SPECULATIVE OUTPUT FLAGGING ─────────────")
    # Inject a mock result that contains forward-looking language
    inner = LLMProvider(provider="mock")
    # Patch mock to return a response with speculative language
    mock_result = {
        "entities": [{"text": "FutureBank", "label": "ORG", "confidence": 0.99}],
        "source_excerpt": "FutureBank is expected to grow revenue by 20% next year."
    }
    provider = GuardedLLMProvider(inner=inner)
    processed = provider._check_output(mock_result)
    print("Speculative language flags:", processed.get("speculative_language_detected", []))
    print("Disclaimer added:", "disclaimer" in processed)
    print("Confidence capped:", processed["entities"][0]["confidence"])


def main():
    _demo_safe_prompt()
    _demo_forbidden_prompt()
    _demo_speculative_output()


if __name__ == "__main__":
    main()
